### ISSUE TITLE
Please rename this project

### ISSUE THREAD

**Issue by Ecco** [M4xi1m3/numworks.js#1]
NumWorks is a registered trademark and is not affiliated with this project in any way. Please use another name.

**Comment by M4xi1m3** [comment]
First, I want to apologize for such a late response.

I know that Numworks, as a company, wants to protect its copyrights and trademarks - honestly, it's pretty understandable, I'd do the same.
The only problem I have with that is that exceptions to trademark exists in France, as stated in [article L713-6 of the intellectual property code](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069414&idArticle=LEGIARTI000006279714) :
> I. - Une marque ne permet pas à son titulaire d'interdire à un tiers l'usage, dans la vie des affaires, conformément aux usages loyaux du commerce :
> [...]
> 3° De la marque pour désigner ou mentionner des produits ou des services comme étant ceux du titulaire de cette marque, en particulier lorsque cet usage est nécessaire pour indiquer la destination d'un produit ou d'un service, notamment en tant qu'accessoire ou pièce détachée.

Here is a translation for non-french-speakers who might find that issue :
> I. - A trademark does not allow its holder to prohibit third parties from using it in the course of trade, in accordance with fair trade practice :
> [...]
> 3° Of the brand to designate or mention products or services as those of the owner of this brand , in particular when this use is necessary to indicate the destination of a product or service, in particular as an accessory or spare part.

I'm not a lawyer, but I'd consider that Numworks.js is falling into that trademark exception. Furthermore, this lib being under MIT license, it isn't developed as a commercial product, but as a FOSS project to make an """open""" calculator even more open. If you still have any complaints, I'd be more than happy to answer them by email.

If you ask again for a change in name, I'll do it. Be aware that the new name might give a bad reputation to your company (I had ideas like MadCalc.js).

**Comment by adriweb** [comment]
`nwjs` is a shorter name that may please everyone ^^'

**Comment by Ecco** [comment]
Hi @M4xi1m3 !

Thanks for your kind and detailed reply! And don't worry about the timeframe, there's no rush :)

I have a different understanding of the law extract you quoted. I believe it is meant to allow a third party to designate an object whose name is a registered trademark.

For instance, according to this law, Apple couldn't prevent an OEM from saying "Our FooBar earphones work with a iPoad", even though iPod is a registered trademark. But I doubt an OEM could manufacture some earphones  and name them "iPod.plug". Otherwise that would just ruin the whole point of registering a trademark in the first place…

The problem here is that you're **naming** your project after our trademark. This make it sound a lot as if it were a project officially endorsed by NumWorks as a company, which it is not. This the reason I would like you to rename this project.

Note that my comment wasn't targeted at the project _per-se_. I think it's a great project, and I'm glad you undertook it. As you know we already have something similar internally. We considered open-sourcing it at some point but we figured we didn't have the bandwidth to do it properly at the moment. So thank you for doing something equivalent!

Thank you very much for your understanding.

**Comment by M4xi1m3** [comment]
Thank you very much for the interest you're giving to this project, I really appreciate it. But...

After reading the laws again, I'd like to point out that [every article from the French trademark laws](https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000039381607&cidTexte=LEGITEXT000006069414) forbids usage of the brand "in business" ("dans la vie des affaires").

Furthermore, similar cases have already been dealt with by the Paris tribunal de grande instance. A good example is the case regarding the usage of the brand "Plus belle la vie" (a well known French TV Shows) by one of their fan for the creation of a facebook group and a domain name (you can read about it in French [here](http://www.sbavocats.com/lutilisation-dune-marque-en-dehors-de-la-vie-des-affaires-est-libre/)) :
> European law provides that in the absence of use in "business life", the owner of a mark is not empowered to prohibit a third party from reproducing his mark, and even in the event of a use aimed at products or services identical to those for which the mark is registered.

The big question now is "Am I in business life?". Neither the European legislator nor the French legislator have defined this term. The Paris tribunal de grande instance gives a definition. For something to be considered business life it must
- Be public, beyond the simple private sphere
- Grant an **economical advantage, either direct or indirect**

As stated before, this library is released under MIT license, meaning **I'm not selling it. I'm not accepting any donation nor getting ad revenue from the traffic on github nor the traffic on the npm repo**. As such, I'd consider that I'm in a non-commercial use of your trademark, which is allowed by the laws.

*If you want to make a DMCA claim on this repository or send me formal notice, go ahead, but keep in mind that we could see each other in court any time soon.*
